### ISSUE TITLE
Deployment errors

### ISSUE THREAD

**Issue by davidglic** [davidglic/beegardenbackend#1]
I'm stuck here. I've been tyring to figure this out from multiple sources--below--but I can't follow anything 1:1 since most of the tutorials either seem to only use one framework or have both react and django in the same .git. I'm pretty much stuck at the pushing code up step, I have the app created on heroku and git set up done.
![image](https://user-images.githubusercontent.com/82845270/125663452-bba22982-69a8-4001-8474-9236a3b7c8f4.png)
https://devcenter.heroku.com/articles/git
https://dev.to/shakib609/deploy-your-django-react-js-app-to-heroku-2bck
https://dev.to/mdrhmn/deploying-react-django-app-using-heroku-2gfa
https://git.generalassemb.ly/cfg-seir-2/nodejs-postgres-heroku-deployment

I'm using react frontend with django-rest api backend.

**Comment by davidmagbee** [comment]
Based on a quick glance at your backend repo you do not have the necessary files to ensure the Python [buildpack](https://devcenter.heroku.com/articles/python-support) will work for your application. Be sure to follow the [docs](https://devcenter.heroku.com/articles/deploying-python) for the service you're using to ensure the most accurate information. Heroku has _great_ docs. @davidglic 

![](https://i.imgur.com/kxkNTUS.png)

**Comment by CRHarding** [comment]
@davidglic were you able to give this a shot?

**Comment by davidglic** [comment]
I have the requirements.txt I sill get the app not compatible with buildpack.

**Comment by CRHarding** [comment]
Do you have a setup.py file and a Pipfile? As per the docs you need ALL three, a requirements.txt, a setup.py, AND a Pipfile.

**Comment by davidglic** [comment]
I got the impression only one was necessary... From what I can tell they are 3 different methods for handling dependencies, but I might be mixed up.  Can you also confirm were they go? In the same folder as manage.py?

**Comment by davidglic** [comment]
I've tried it in the django root directory, the .git root, and the pyevironment root.

**Comment by CRHarding** [comment]
If you read the bottom of the picture that David posted: If none of these files is present in your app's root directory, the Python buildpack will fail to identify your application correctly.

**Comment by CRHarding** [comment]
Those files need to be in the git root, so where your .git file is located. Heroku uses git to manage a bunch.

**Comment by davidglic** [comment]
How do I make the other two files then?

**Comment by davidglic** [comment]
It can't be all three files because it pipfile is only used for pipenv which we are not using. It's the requirements.txt equivalent for pip i think.

**Comment by CRHarding** [comment]
https://duckduckgo.com/?t=ffab&q=what+is+a+setup.py+file+heroku+django&ia=web

**Comment by CRHarding** [comment]
You were completely right, you only need a requirements.txt file, but you're going to need to have the file tracked by git, for heroku to hook into it. Have you git added and git commited and the pushed to heroku master / main?

**Comment by davidmagbee** [comment]
This is a great resource for [configuring Django apps with Heroku](https://devcenter.heroku.com/articles/django-app-configuration).

Also, this [article](https://towardsdev.com/django-react-app-from-scratch-to-deployment-part-1-8a2fa9a97f1
) has a nice breakdown of the `settings.py` file that may be helpful.

**Comment by davidmagbee** [comment]
Also... can you `push` your latest code so we can see current files? @davidglic

**Comment by davidglic** [comment]
Latest code pushed.

**Comment by CRHarding** [comment]
Is there a requirements.txt file where there is a .git folder?

**Comment by davidglic** [comment]
Okay, it was there but it wasn't git added because I was doing the "add ." from a higher directory.

**Comment by davidglic** [comment]
That worked, now I'm getting new errors to chase.

**Comment by davidmagbee** [comment]
FYI, we can't close these tickets since they're your repo. If this issue is resolved don't forget to close the issue ticket.
