### ISSUE TITLE
Weird CORS error.

### ISSUE THREAD

**Issue by davidglic** [davidglic/beegardenbackend#2]
One last quick error before I freeze my code. I finally got the backend deployed and working on heroku, did a quick deploy of the front on surge. If I run the front on my localhost:3000 all interface with the backend works. If I run the front on surge, https://rebel-friends.surge.sh/ , then every backend API call works except on the front end except on the landing page I get a cors error for the news articles on the bottom.

Access to XMLHttpRequest at 'https://littlebeegardenbackend.herokuapp.com/articles/news' from origin 'https://rebel-friends.surge.sh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

route is correct, origin is in white list in django settings, all other api routes and calls work from surge. I googled a bunch last night but couldn't find any similar errors.

**Comment by davidmagbee** [comment]
Is all current code pushed? @davidglic

**Comment by davidglic** [comment]
Apparently not. It is now.

**Comment by davidglic** [comment]
https://github.com/davidglic/beegardenfrontend
Just in case you need the frontend code in a handy link

**Comment by davidmagbee** [comment]
[django cors error](https://dzone.com/articles/how-to-fix-django-cors-error)
[managing settings.py](https://agileleaf.com/blog/a-better-way-to-manage-settings-py-in-your-django-projects/)
[React, Django, CORS](https://medium.com/@zoltankohalmy/react-and-django-57f949b0f012)
[the cliche stackoverflow post](https://stackoverflow.com/questions/44037474/cors-error-while-consuming-calling-rest-api-with-react)

**Comment by davidmagbee** [comment]
Any luck @davidglic ?

**Comment by davidglic** [comment]
It is browser related, chrome specifically. If you go into incognito on chrome, it works. From Edge, it works. 

Edit: Just cleared my cache based on a recomendation for searching the error with that language and it fixed.
